image: blang/latex
build:
  before_script:
    - virtualenv venv
    - . /venv/bin/activate
    - python -V
    - sudo apt-get install tesseract-ocr
    - sudo apt-get install libtesseract-dev
  script:
    - pip install pillow
    - pip install pytesseract
    - python MCapp/mcapp.py
    - python MCapp/testOCR.py
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
