image: blang/latex
build:
  before_script:
    - virtualenv venv
    - . venv/bin/activate
    - python -V
    - sudo apt-get update
  script:
    - pip install -r dependencies.txt
    - python MCapp/mcapp.py
    - python MCapp/testOCR.py
    - python3 MCweb/MCwebDjango/webtests.py
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
