image: blang/latex
build:
  before_script:
    - virtualenv venv
    - . venv/bin/activate
    - python -V
    - apt-get -qq install -y  tesseract-ocr libtesseract-dev
  script:
    - pip install pillow
    - pip install pytesseract
    - python MCapp/mcapp.py
    - python MCapp/testOCR.py
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
