image: blang/latex
build:
  script:
    - pip install pillow
    - pip install pytesseract
    - apt install tesseract-ocr
    - apt install libtesseract-dev
    - python MCapp/mcapp.py
    - python MCapp/testOCR.py
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
