image: blang/latex
build:
  before_script:
    - virtualenv -p python3 venv
    - . venv/bin/activate
    - python -V
    - sudo apt-get update
  script:
    - pip install -r dependencies.txt
    - pip list
    - cd MCapp
    - python tests.py
    - cd ..
    - python manage.py runserver
    # - python3 MCweb/MCwebDjango/webtests.py
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
